* features
next episode:
@spader 3/1/2020: add time parameter to animation frames
@spader 3/1/2020: port tile selector
@spader 3/1/2020: components you will probably need for level 1...collision,
interaction, task, tile, dialogue, state
@spader 3/1/2020: autogenerate tile classes, probably with like a lua for loop?
tdengine.tile?
* closed
@spader 8/27/2020: scenes
Idea 1: Each scene is a Lua class. This doesn't work with the editor, or with
saving stuff out. You want data, not code. When stuff changes during the game,
you need to save that, and code won't work for that. 

What entities exist?
What are their locations?
What tiles exist?

Start by making the infrastructure: A list of scenes in Lua. A SceneManager in
C++. A scene class in Lua. A basic file format (in Lua) to describe what's in a
scene. Some functions on the scene class to read it in and build the scene --
what entities exist and where they are. In the future, maybe save / load
functions on entities. 


@spader 3/1/2020: Get the rendering system right. Ideally, there's a clever way
for every entity with a GC to register itself with the rendering engine. You
could probably do that in the GC constructor -- just call into some API that you
expose in C++.


@spader 3/1/2020: Inputs are kind of fucked right now. What's a good way to
handle chords of all kinds (shift included)? How do the game layers and scripts
read from the input buffer? n.b. this isn't quite done because I haven't
/implemented/ when masks are applied, but all the logic is pretty much there


@spader 3/1/2020: could prob autogenerate imgui stuff for entities
for member in entity:
  if type(member) == function then pass end
  if type(member) == number or string then display it
  if type(member) == table recurse


@spader 3/1/2020: moved engines/managers to jblow style functions
@spader 3/1/2020: fixed how inputs are masked to different layers, added inputs
to exported API
@spader 3/1/2020: found some GLFW key binding definitions
@spader 3/1/2020: wrote some basic camera code
@spader 3/1/2020: fixed the imgui binding generator 
@spader 3/1/2020: figured out how to wrap some of the stuff that doesn't cover.
@spader 3/1/2020: started porting the editor over to lua
@spader 3/1/2020: wrote a basic entity viewer 

@spader 3/1/2020: entity:print_once()
@spader 3/1/2020: tdengine.get_entity(name)
@spader 3/1/2020: finish off bitmask logic for inputs
@spader 3/1/2020: shift map

@spader 11/6/2019: Put some more thought into the API, and the separation of the
engine from the game. Do I want to make the engine as a DLL? Is that going to
supremely fuck all of my precious debuggability? As an alternative, I could
leave the game and the engine as one binary, but separate the code out such that
it would be really easy to snip them apart when the time comes. Binaries and
consumption aside, the real reason I want to do this is to get a better handle
on the responsibilities of each part. What is the core engine actually doing,
and what parts of the code truly belong to my game? Still in the back of my mind
have the idea of someone else using this engine. Wouldn't it be cool if this
engine was a super lightweight one that you modified by (gasp) actually touching
the source code? Actions and components are packaged up with it, but you can
easily mod it to allow user ones, too. 
* thoughts
** 03/02/2020: Engine Architecture
@spader 3/2/2020: I want to avoid writing a lot of wrappers. Ideally, adding a
binding to the engine is one or two files. Most of the bindings into the engine
are going to be pretty thin wrappers. The layers look like this: 

Lowest level: ENGINE. 
Inside here, you have all the subsystems that actually do the work. The
rendering engine, the physics system, etc. 

Next level: API. 
Thin wrappers which are directly bound to Lua. The purpose of these
is to keep my Lua API nice and stable, and let me do whatever tricky things I
want with function signatures. Varargs, template stuff, whatever. Just register
a wrapper to Lua. 

Next level: SUGAR.
Thin wrappers in Lua. The purpose of these are purely sugar. For example, the
C++ API will take in integer IDs for entities, but I want to pass in the Lua
table because that looks natural. Write a wrapper that takes the Lua table and
forwards the ID to C++. 

Last level(?): COMPONENTS.
Components shouldn't be wrappers around the API per se -- they should put some
useful functionality on top of it. In other words, they talk to other components
and then decide what API functions to call. 

That doesn't seem too arduous. 
* gameplay
** types
The types are, flavor wise, supposed to represent the reflections of different
pure forms onto the physical realms. All things exist purely through dogma. The
precise qualities that make anything itself come from this. When they're
filtered down to the physical plane, some of these characteristics get lost. 

Battles involve creatures that are powerful manifestations of these traits. They
are also filtered when they enter our world, but their concentration is much
higher and they are therefore a more distilled representation of them. Because
they are so distilled, they can tap into other aspects of that trait that
regular things could not -- namely, pulling that essential force for battle. 

** [LG] logic
The intelligence of man. 

This type is good at indirect attacking. The first thing that means is that its
attack-oriented creatures are good at special attacking. No grapplers here. The
second thing is that its creatures get good support moves. 
- Stat boosting moves
- Substitute
- Baton Pass
- Trick Room
- Roar

Their typing defensively is a pretty clean 50. Their typing offensively is
probably closer to a 60, preferring to use power over type coverage to get the
job done
** [DS] dark spirit 
The evil nature of man. Corruption, greed, sloth, sadism, power, intimidation.

This type has a lot of offensive support moves and a lot of mix ups. Solid
STAB moves with fair coverage, but mostly based around the idea that you can
morph them into a lot of things. This would be a good place to have a utility
creature that can sweep or take on a number of specialized defensive roles. 

Inspirations:
Taunt Wisp Mew
BW Gliscor
BW Sableye
ADV Gengar
DPP UU Crobat
DPP UU Froslass

- Taunt
- Will-o-Wisp
- Explosion
- Destiny Bond
- Knock Off
- Pain Split
- Trick
- Drag Down (Ability): On turns where this creature uses a support move before
  an opponent can attack, creature takes half damage. 
- Spite (Ability): Any creatures active at the end of the turn lose 1/16th of
  their health, including this one. 
** [LS] light spirit
The good nature of man. Soft kindness, mothering, empathy, joy.

This type is where your pink blobs live. It has a lot of defensive support
moves. They don't carry momentum well in and of themselves, because they lack
the tools to directly pressure the opponent. Instead, they try to slow the game
down and remove key threats from the game. 

Defensive Dragonite

- Wish
- 50% recovery
- Seismic Toss
- Aromatherapy
- Encore
- Screens
- Calm Mind
- Good coverage but poor offensive stats
- Natural Cure
- Regenerator
- STABs that have useful secondary effects (e.g. Scald)
- Resilience (Ability): All passive damage done to this creature is halved. 
- Gift of Health (Move): Instantly heal 1/4 of any teammate's health
- In Tune (Ability): When this creature heals, it receives 1/10 more health than
  normal. 
** [RS] red spirit 
The passionate nature of man. 
** [EA] earth
The essence of physical material. (might make this a 'materia' type, give
different flavors like air and water)

This type is all about the physical attacks. Low special stats, both offensively
and defensive. Flavor-wise, focuses on moves that manipulate the non-living
material of the Earth. Earth will be a really good typing defensively and
offensively. Offensively, the problem will be that they don't get good coverage
moves -- maybe something like Rock Slide + Earthquake in ADV, but even that
might be a little too good. One or two key weaknesses that you can exploit (one
physical, one special?).

Inspirations:
BW Landorus-T
BW Excadrill
ADV Flygon

- Earthquake
- Swords Dance
- Lead Smoke (Move): The next creature to enter the field will lose 1/8 of its
  health
- Rock Slide
** [MC] machinery
You ain't machine and you ain't land. Machines are more organized than the chaos
of material, yet their organization holds a cold acid edge that is not truly
alive. Creatures of machine are extreme. They do few things, but they do them
well. Their stat spreads are heavily skewed to one of the few things that they
do, and so are their movepools. Their defensive typing is poor, but their
offensive typing is very good. They are bound by almost all things -- water,
material, human nature and ingenuity -- but at the same time they bind these
things as well. 

Visually, they'll all look like machines, but mechanically they'll focus on one
or two aspects of the game and be really good at that and pretty bad at
everything else. It will be hard to make these usable.

Inspirations
DPP Azelf
ADV Magneton
BW Bronzong
DPP Lucario
BW Gothitelle
ADV Forretress
BW Sableye

One that focuses on entry hazards
One that fucks up a fairly common defensive type
Glass cannon sweepers 
Suicide leads (hazards/screens/boom)

** [FR] fire
** [WA] water
necrotic? 
the mountains
god 
psychedelics
philosophy
science
art
fire
cells
ice
electricity
time
void -- things that completely lack type 
psychosis
animals
sages
** [FA] fauna
The spirit of the animal. Brutish, petty, yet surprisingly clever at
times. These are things that can hit you pretty good. Usually not a ton of
tricks up their sleeve -- they might have mixups, but it'll be clearer what
their options are from the things around them (e.g. pretty easy to spot a mix
lax). 

Inspirations:
ADV Tyranitar
ADV Metagross
ADV Snorlax
ADV Heracross
DPP Gyarados
** [FL] flora
The spirit of floral nature.

Inspirations:
Ferrothorn
Celesteela
Tornadus-Therian

This type is all about momentum (think about the beautiful flowing momentum with
which plants live). Floral types get lots of annoying support moves and
abilities
- Leech Seed
- Protect
- Toxic
- Stun Spore
- Toxic Spikes
- Spikes
- Iron Barbs (physical / special)
- Sap (Ability): Transfer 6% health from opponent to user at the end of each
  turn.
- Return to Nature (Ability): Every turn, regardless of whether this creature is
  active, it gains 1% of its health back
- Knock Off
- 50% Recovery

Their operating principle is to, at worst, make a trade. Every time a Floral is
on the field, SOMETHING should be happening to your advantage (even if the turn
itself is a net negative). 

** [DG] dogmatic
The pure essence of dogma. 

This type is the most well rounded type in the game. It provides a few well
rounded STAB moves, but more importantly offers key resistances and few
weaknesses which makes it highly sought after defensively. Dogmatic creatures
generally rely on their potent movepools to output lots of damage, and they use
their good typing to be excellent checks to other offensive threats. 

Inspirations:
BW Latios
BW Hydreigon 
BW Garchomp
ADV MixMence (closer to this in terms of power)
DPP Tyranitar

- Fire Blast
- Draco Meteor
- Brick Break
- A few weak but really useful coverage moves for mix-ups
- 100/90/90 defenses

** type chart
|    | LG | DS | LS | RS | EA | MC | FR | WA | FL | DG |
| LG |  0 |    |    |    |    |    |    |    |    |    |
| DS |    |  0 |    |    |    |    |    |    |    |    |
| LS |    |    |  0 |    |    |    |    |    |    |    |
| RS |    |    |    |  0 |    |    |    |    |    |    |
| EA |    |    |    |    |  0 |    |    |    |    |    |
| MC |    |    |    |    |    |  0 |    |    |    |    |
| FR |    |    |    |    |    |    |  0 |    |    |    |
| WA |    |    |    |    |    |    |    |  0 |    |    |
| FL |    |    |    |    |    |    |    |    |  0 |    |
| DG |    |    |    |    |    |    |    |    |    |  0 |

** moves
- Screens
- Wisp
- Toxic
- Thunder Wave
- Sleep Powder
- Refresh / Heal Bell
- Substitute
- 50% recovery
- Rest
- Haze
- Protect
- Perish Song
- Taunt
- Destiny Bond
- Focus Punch
- Baton Pass
- Doom Desire
- Encore
- Explosion
- Fake Out
- Hidden Power
- Magic Coat
- Memento
- Healing Wish
- Trick
- Pain Split
- Skill Swap
- Super Fang
- Thief
- Giga Drain
- Sedate (Light Spirit): User cannot use any attacking moves for two
  turns. Always goes last. 
* plot
Open up in an everyday elementary school. Rows of particle boards desks, wide
rectangular fluorescent lights, concrete painted white on all four sides. The
kids are all sitting, faces down intently at their exams. They can't be more
than ten or eleven years old. One boy nervously chews a pencil while he tries to
work out how to add fractions for the hundredth time. All is as it should be.

Except there is pre-pubescent trouble brewing. D. Boon, glasses thick as
coasters, rail thin, slightly hunched shoulders, sits at his desk trying
desperately to pretend that he hasn't finished his exam. He traces his pencil
around the same section of the page, writing, erasing, leaned over in feigned
concentration. But he's not doing a very good job of it, because he feels
something damp stick against his shoulder. The dreaded spitball. It would seem
like someone else is finished with their test too -- finished, or doesn't care.

"Lemme see your /answers/, Boon." It's O'Doyle. He's big for his age, already a
solid five nine, and fat to boot. His face shows the promise of acne, his
jawline the promise of coming in -- puberty is soon to come to him. But for now,
his malice is merely that of a childhood bully. Nothing so insidious as the
social schemes of high school. 

O'Doyle is a regular thorn in Boon's side. He's smart enough to know how to push
Boon's buttons -- not just some brainless mudslinger. And more importantly, he's
physically imposing. He's always saying some shit to him, not just isolated
incidents of violence. 

"..." 

Boon stares ahead intently, focused /hard/ on not reacting. He wants to get the
teacher's attention, but she's slumped back in her chair, dozed off reading a
novel with a well-oiled Scottish man on the cover.

/Just don't say anything and he'll go away/

"Come on Boon, if I don't pass the fifth grade my dad'll /beat/ me." He delivers
it with the quality of a joke he knows is too black for someone his age.

A soft poke comes from from Boon's other side. "Yeah, Boon, I need the answers
too. Heh heh." Tweedle-dee and Tweedle-dum, O'Doyle and Levi. Dynamic duos for all
time. Levi is a /lot/ dumber than O'Doyle, but also morbidly larger and
decidedly meaner.

POKE. The first one just got his attention, but the second one breaks
skin. "STOP," Boon can't help but cry out in pain and frustration. The teacher
snaps awake. 

"WHAT is going ON? You're supposed to be taking a test!"

Boon doesn't say anything -- he knows she won't punish him, but he doesn't want
to deal with the two of them. He puts his head down and shrugs
half-heartedly. O'Doyle and Levi find a sudden interest on the cement blocks on
the other side of the room. Mrs. Miller sees their guilt and says, "Let me speak
to the three of you. After class."

--- 3 PM

Cut out, cut back in. Mrs. Miller is finishing up some lesson, but the bell cuts
her off before she has a chance to finish. Boon tries to slip out quickly, but
she catches him. She sits the three of them down in the front row and starts
asking questions. The story comes out -- she takes Boon's side, of course, as
the sweet, bright boy. She asks to see Boon's side, and when she sees a prick of
crusted over blood, she becomes serious. 

"This is worse than I thought. You realize what this means, right? This means
you committed a /violent act/. I have no choice but to suspend you both for a
week."

"A week?!", O'Doyle cries out. "But my dad's going to kill me! Please,
Mrs. Miller, I'll do anything, I'll even apologize to Boon here. Watch: Boon,
I'm sorry." 

"I'm sorry, Richard, but there's nothing I can do. It's county policy. Now you
kids go before the buses leave."

--- Outside the classroom

Boon hangs back for just a minute, tying his shoe more slowly than he ever has
before. He finally leaves, starts down the hallway, and almost makes it to the
bus parking lot. But he gets stopped -- by who else? And they're mad, this
time. 

"I'm done screwing around. I'm gonna show you what happens when you screw with
someone you shouldn't!"

Levi sneers at him and pushes him in the locker. O'Doyle throws a sucker punch
as Boon cowers back into the wall of lockers. Levi picks him up and disables
him by putting him in a bear hug. They walk the way they came from, past a few
classrooms, and stop before a janitor's closet.  

"It's Friday. Let's see how you like being suspended this weekend."

With that, he throws Boon into the closet. His vision is starting to fade. On
the ground, he sees Levi walk up and loom over him. He didn't realize how big he
was. He wonders if his dad is disappointed that he's not bigger. He wonders
what's for dinner. How's he going to turn his homework in tomorrow? Wait, isn't
tomorrow Saturday? Or is it Tuesday? He barely has time to realize that he's
blacking out when Levi rears his heavy, booted foot back and and gives him

One.

Last.

KICK.

"Don't mess with me, son."

--- An Indeterminate Amount of Time Later

Boon wakes up. He's in a place that looks like 

limbo. it's a place where the souls of fifth graders are trapped when they
can't ascend to middle school. some of them got held back -- their minds and
souls couldn't recover socially from being a sixth grader in fifth grade. some
of them moved away and could never adjust to their new lives, clinging to the
brief happy days at the end of their childhood. some of them died. but for
whatever reason, their souls remain here at the bridge between fifth grade and
sixth grade. 

all of this twisted world is a school -- of course it is. dungeons are made of
wings of the school. limbo, then the lower classmen, and then finally: the eigth
graders. the big shits. each dungeon is made of rooms of the school. classrooms
where students and damned teachers reside. the janitor's closet, which might
have an enemy like a huge lice. the nurse's office. 

you must make it to the principal's office at the end of eighth grade hall to
battle the final boss

something isn't right here. it's twisted, inverted. things have a set way of
working here, and it's becoming /wrong/. turns out, that thing is levi and
o'doyle becoming the kings of hell. they're the final boss.

you have some sidekick who cheerfully tells you about the world you inhabit. 

creatures are the souls of everyday things. simple things, maybe even things
that aren't jazzed up at all. like, a dog that is just a dog. a chair. slightly
anthropomorphic, maybe. 

the gym, filled with step stools and racks of balls. slippery with floor
polish. 


