* tags
@detail
@sidequests
@continuity
@dungeon
@note
* small themes and ideas
- the small, everyday lives of people
- alone, picking up your room, what are your thoughts?
- you become absorbed in your routine, and it feels embarassing
- your mom going to the store to pick out a small gift for you to open on
  christmas
- even in evil institutions, there are good people
- characters who have well defined motivations. it doesn't have to be crazy
  complex. it just has to be some self-consistency wrapped up to be human.
- slowly uncovering documents of the founding fathers
- "and my father around didn't want me no more"
- "quick time events", but instead of testing button mashing it's forcing you to
  make a split-second decision that you may regret later.
- The Black Hebrew Israelites, or some other equally ridiculous group.
- all of the cheap comforts you and i enjoy are the product of someone else's
  exploitation
- watching the main villain from afar, menacing
- dogmatics
- how easily we fall into routines
- every day you use people, you use your uber driver, you use the cashier at the
  restaurant, they put on a face for you.
- musical themes when you do something good or bad
* sidequest ideas
*** the crier
you stumble into a pedestrian. he seems almost raving mad. he is onto the
conspiracy. he knows that magic exists -- not beyond a shadow of a doubt, but
enough to make him lose his mind with the sheer possibility. he brings you back
to his house where he shows you wild notes strewn everywhere. he seems on the
brink of some great discovery and some great publication. you must choose
whether to let him live and perhaps blow everything up or to take an otherwise
innocent life.
* visual ideas
- flashbacks with the screen darkening around the edges, "tape flicker" popping
  in and out, occasionally glitching
- mana spark blocky characters and more detailed world stuff. also their color
  pallette. 
* old stuff
** lifestyles of the poor & unknown
sewell runs and ends up in a poor part of town. he gets stopped by two people
outside washing their cars. they look at him and can see that he's in
trouble. they take him into their house, telling him that they have often met
people who have no place to go. they tell him that they don't care what he's
running from, but that he can stay there until he has another place to go. they
begin chatting. sewell learns that they are poor, living on the free lab-grown
gruel that the government provides for its ultra poor. they are living out of
essentially a one room shack, sleeping on the floor. they're married. they've
both suffered completely debilitating injuries. sewell becomes angry that the
government isn't doing more to help them. he sleeps there for the night and
wakes up to a message that there's an underground lair he can go to owned by a
slightly unfriendly group of militant revs.

the message-giver says that the group is kind of notorious in the area. a bit
like brutal robin hoods. happy to steal, murder, and kill for the good of the
community -- but what the good of the community means is entirely up to them and
sometimes not righteous. he should check out the area that they're in first to
see if he can learn anything about them

@sidequests

when he gets there, he gets greeted by a gruff, scrappy old-ish man. kind of
ratty. the man seems very self assured, someone who won't take an ounce of shit
for anyone. he makes it very clear to sewell that the only reason that he's here
is because the base could use an extra pair of hands, not out of any
kindness. he brings sewell back to the main office.

he lays out their plan to sewell. tonight, they're going to put a big swipe at
the government. the government delivers food, milk, diapers, basic supplies to
this neighborhood once a week on this day. they're going to the warehouse where
they keep all of this stuff, kill everyone there, and take it all back to their
base. their goal is to get the 'peasants' sufficiently hungry, spin it as the
government taking this stuff away, and then use the peasants' desparation to
make them riot and cause a scene as a tool of distraction.

sewell is pretty aghast at this, but he gets an ultimatum: you know too much, so
help us or take a knife across the throat. he decides to aid them.

@dungeon: a small one. no puzzles. 
they arrive at the warehouse at night. it's a ways out of the city, and cicadas
are chirping when they arrive. the camera pans out to men in uniforms stacking
boxes of supplies onto the beds of semi trucks. the ratty man reiterates that
the plan is to kill everyone magically, not leaving a single trace or
survivor. they want the government to be confused. there aren't many men here,
but there are a few fairly powerful guards. you go through the base until you
reach the back corner. the ratty man and a few other cohorts have trapped the
last remaining people. there are a few more guards who can use magic protecting
some warehouse workers. sewell sees the last guard trying to escape and battles
him.

once everyone is dead, sewell sees the ratty man shaking. he says how he hates
the government, how it consumes him. he wishes it didn't have to be like this,
and he remembers a time when it wasn't. they've taken so many people from
him. sewell tries to comfort him, and the ratty man backhands him across the
face. all silence as the revs. pack the food into the trucks and ride.

** boon's vignette
- pre
  - a vignette plays of an older man coming home to his wife, her surprising him
	with his grown children. they sit down to have dinner and they laugh.
** the young boys
evans meets a child of the revolution. the child is all bluster, he's fourteen
but he wants to die for the revolution. he looks up to evans. he tells evans
that he and some of his friends are going on a secret raid, one that no one
knows about. they're going to try to kill some police officers who'll be
guarding a political event. evans threatens to tell the adults, but they say
they'll just go now and die for sure. evans decides to go with them to try to
save them.

@dungeon: also no puzzles. relatively early into the dungeon this happens, then
you slog through until the end
they arrive at the event. evans has given them specific instructions to help
keep them alive. after evans takes out a few isolated guards, one of the boys
comes up to him, beaten and bloodied. he says the other boys have been
captured. he saw where they led them.

when he reaches the end of the dungeon, he hears someone talking to the
boys. the person is apologizing to them. when evans comes in, he explains to him
that he wasn't powerful enough to hold them off until others came to subdue
them. he had to cut them off from the source -- effectively, killing them. the
boys seem lobotomized. the government man lashes out at evans, asking how they
could keep sending children like these to do their dirty work for them. evans
says he doesn't know what she's talking about and that these kids came of their
own free will. he says it's not the first time this has happened. you may decide
whether to kill him or not.
*** vignette
- pre
  - a young man with a group of others beating up a homeless person.
- post
  - he returns to his home, dilapidated and disgusting, where his father repeats
    the same curse as the young man did to the homeless person

** wilder tanks
boon asks if it's possible to just forget this happened and go back to normal
life. ike says that if he escaped detection this long by some means, yeah, maybe
that fluke would hold out. but the more important thing is that you don't *want*
to go back. boon asks how he can say that so easily when he's got to leave his
whole life and family behind? 

ike says that the two of them must go on a short journey, and then he
will let boon rest as long as he needs before making a decision. he asks if he
knows how to battle. boon says yes. ike says that he'll go tell one of his
employees that his nephew came from out of town and they're going to get a quick
lunch. 

they walk off to a large, grey factoryesque place. they slip through a fence in
the back, and ike tells him that what he's about to see is how the
government powers everything boon sees in the world around him.

@dungeon factory design (puzzles? battles)
they walk through the factory. there are guards there, and you battle them. you
come down to a room filled with rows of tanks filled with fluid, emitting
fluorescent blue light. ike explains what they are: slave tanks. captured
wilders who are too late or too hostile to train get their magical conscious
sucked from them and linked to others of their kind to produce the comforts we
rely on. he says to boon, you are complicit. but you can help us. they return to
the hotel.
** the police chief
he lays out their latest plan to boon: they have information that there is a bit
of inner politics going on among the enforcers. killing the man currently in
power would likely destabilize the police system, and give them some breathing
room. and if everything goes perfectly, the whole thing could implode.

he tells boon that people are rallying at their main base in the forest. they
live in the forest and eschew common pleasures in exchange for peace of mind.

@detail what happens in between leaving the hardware store and getting to the
forest? nothing big plotwise but..
@sidequests

it is the night that the police chief will die.

at night, they rally the small group that's going to do the deed. they begin to
read strange, archaic sounding rites. boon asks what they are. they say that
they are remnants from an ancient magical culture. all they have are cryptic
scraps of their existence, but they all point to the prophecy that magic will
destroy humanity utterly and completely. they speak these rites before they
kill. boon joins them in speaking them.

@detail: inject some big plot here
@dungeon: no 'big' puzzles here, just battles -- maybe activate some switches on
the second floor. 
they go to the police station or wherever he is officed. boon easily slices
through the opposition at the station. when they reach him, he sounds scared but
firm, and they fight. as you leave his office, the closing vignette plays.
** a chance encounter; the forest
you come to find sewell in a bar. or a coffee shop. i don't want to make it seem
like this one thing destroyed him. surely as a rev. he has seen some dark
shit. anyway, he gets a message from evans to meet him at the bar.

he meets an old woman there. she is a mystic -- magical. she doesn't fully
understand what magic is. she gives prophecy. one will become two, then
three. @continuity the split between the three main characters and their
ideologies. she says he seeks one who is very powerful, one who cannot be
controlled, one who will break what he loves. she says that by seeking him out,
he will fulfill this prophecy. she tells him that to find him,they must go to
the forest (revs are hiding somewhere in the forest, but there is bad magic
there)

she hands him an amulet of power and leaves.

evans walks in. the two of them discuss what happened to them. they say that
they are unhappy with the information that was withheld from them, that this
might not be something they want to be a part of. they do not make definite
plans, but they have sympathy for each other. sewell tells evans of what the
woman said. they agree it must be about boon, but they also agree he holds too
much potential danger to be left alone. they decide to go search for him and
head to the forest.

@sidequests

@dungeon: more traditional, light puzzle elements
when they approach the forest, they both agree that something feels off. there's
bad magic in the forest. kind of like something in the 2nd dimension can't
comprehend 3 dimensional aspects of things, those without access to the source
are unaffected by the forest. so by and large, it appears to be a normal
forest. there are no rumors of strange happenings or hauntings. there are many
battles in the forest. the off-feeling gets worse as they go in. this all
culminates in battling a bad ass forest demon thing. this'll be the first part
where the second act is introduced (killing the ancient magic) -- the forest
demon, upon dying, will croak out something about his master.
* backstory
** the savior
also, an ancient backstory of the few who were left and how they rebuilt
the human race in secret. reading it would be cool, like reading how the
founding fathers thought of philosophy and democracy. now, parts of it seem
primitive, but other parts at the same time seem prescient. like they were
obviously very smart people, but there were things they just could not
forsee. maybe reading discovered papers, maybe even flashbacks where they
encounter the forsaken to understand how the original rift divided. one figure
who sacrifices himself to hold off the forsaken long enough for society to
rebuild if everything goes perfectly. slowly piecing together this plot from
clues left in reality by the savior.

flesh out above. so i'm thinking that this happened near the times of the
greeks. before the golden era of greek culture, magic was discovered. since it
was so new, its users were extremely weak. they could not summon creatures for
battle. most of the interesting technology, which works by manipulating the
currents of magic that flow through the physical world, were undiscovered, since
there requires a certain amount of power to be able to even sense these
currents. but what they did gain was insight. having the ability to use magic
lets you see into the universal magical nature which imbues all
things. everything has a bit of magic in it. the magic is its true perfect
form. what we see in the real world is the reflection or shadow of that. when
you get access to the magical source, you can sense that perfect form, which
gives you insight to how the shadow behaves. that's why the greeks had a lot of
cool insights about logic, math, and inventions that /could/ be. they didn't
invent computers or machines really, but they saw how those things could be
constructed (or basic forms of them) through magical insight.

here's where a bit of alternate history has to come in. since there was no near
extinction event after the peak of greek culture, have to invent one. the greeks
became strong enough to raise the notice of beings that live entirely on the
magical plane. these beings had never encountered any other creature that could
use magic, so they just let them be. they sent down people under the guise of
humans to spy on them. it would be cool to have those humans be some famous
historical figures. the greeks eventually gain enough power to become a
technological society, still living in peace with the magical beings (peace
being not the right word, since they don't know they exist). they start to
invent things like computers, they invent strange means of locomotion, and they
begin to conquer the world. i would like this to be the era of alexander the
great. compared to the rest of the world, they are gods among savages. it's
basically a modern society.

the dam breaks, though, when one man comes of age. he is the most powerful
dogmatic humankind has ever known. he has the ability to see the flow of magic, to
manipulate those flows. when he does so, he taints the magical source. it's like
getting a shock of electricity for the magical beings. and moreover, his power
is exponentially increasing. he quickly approaches the level of magical power of
the magical beings, and then surpasses it. he's like a magnifying glass and
magic is the sun. the magical beings realize that the source is permanently
tainted, and to prevent further damage they have to eradicate mankind. most
people across the globe are slain before it comes down to the ancient
greeks. the dogmatic understands what is happening, and begins to formulate a plan
to save humanity.

he realizes that he is not strong enough to take all of them head on. but he
also realizes that his power surpasses that of any single one of them. he has
access to things which they do not. they poke and jab at one another, until
finally the last battle comes. he's realized that there is only one way that he
can save humanity: link with every existing human dogmatic to fully taint the
source and change the flow of time. they all completely burn out their souls in
the process. the magical plane becomes infected with many beast, feral,
powerful, unthinking. the earthly plane also becomes broken. the history of time
is rewritten. it exists in a shadowed image to the true history (the greeks
still make mathematical and logical discoveries, alexander still attempts to
conquer the world), but the means of how they do it change. people (including
all dogmatics) are rewritten out of time from the very first moment of time, all
of the butterfly effects that lead to humans gaining the power are changed in
perfect unison to manipulate the universe itself. when it's over, the split
timeline comes to exist just as the timeline in our real out-of-game
world. history progresses exactly the same as it did in real life. until a
magical child is born one day...
** the prophecies
some of this was set up by the savior, who set events into place ages ago. he
left clues hidden in reality -- hidden enough that the forsaken could never find
them, but hopefully decipherable to a dedicated human.

ideas
- he befriended a forsaken. the forsaken told the savior of its plan to aid the
  humans upon its death. "you will be saved by one imbued with the spirit of an
  outsider"
- betrayal
- hints about the true nature and motives of characters.
- oblique references to decisions you will have to make
- descriptions of boon
- misleading things? e.g. describing what would appear to be the main villain as
  the bringer of evil, only to have it subtly refer to another character who is
  secretly evil.

@detail
once these get fleshed out, i need to inject them into the story. who gets what
scraps and when?
** the return of dogmatics + the revolution
the revolution has a storied and complicated tradition. dogma began to rise once
more approximately four hundred years ago. the beginnings of understanding of
chemistry, physics, cell theory, etc. on a hard factual (rather than intuitive)
level was a direct result of dogmatic influence and is our best indicator as to
its return.

however, even though dogma has an exponential curve of increase, it compounds
very slowly at first. people, just like the ancients, didn't understand that
their flashes of insight were dogmatic in nature, or even that dogma
existed. the benefits of linking people together (both in our realm and
dogmatically) were not realized until much later. even still, the increased
intellect and insight that dogmatics had over regular people meant that after a
couple hundred years, dogmatics had all filtered up to the top of the
businesses, governments, and personal organizations that more or less made
decisions for the world.

more recently, around WW2, an awakening happened. this was not one particular
event -- it just refers to the time period where dogmatics realized that they
were not normal people with ordinary insights, but people with powers that were
traditionally supernatural. the key insight from this period was that there were
currents of dogmatic power (akin to EM waves in our world) which could be
harnessed to affect arbitrary change on our reality. the first application of
this: the computer. a machine which could infinitely manipulate the fundamental
rules of logic. the computer fundamentally changed the way that society existed,
but ultimately the dogmatics in power across the world understood that this was
the tip of the iceberg. arbitrary change means arbitrary -- it was only a
question of harnessing the currents and stringing them together in complex
ways.

now, just like a computer, just because it is turing complete doesn't mean that
it is physically possible to calculate anything, or that there is any guarantee
that it will be done quickly. these dogmatic currents are similarly
'complete'. the world's dogmatics were making exponential progress on figuring
out more and more complex configurations and techniques and affecting larger and
larger changes on reality -- until they found the prophecies.

the first prophecies they were found were ominous -- but also extremely vague,
lacking in context, and occult. some of them were completely nonsensical:
do not loosen the tap on the tankard lest ye understand the maiden
...and the cliff's bottom will turn to soft mud for but a split moment...
look to them and study them for they may yield your salvation
the historian lies in the grass but he be no snake

some of them were magical incantations -- of these, some were useful, some did
nothing. as more of these scraps came in, the prophecies themselves seemed to
lead self-reproducingly to yet more of their own kind. the picture began to fill
in. seemingly everything existed in reference to these prophecies
ancient works of history and literature
names of towns
religious figures
the lives of completely obscure people (their actions and lives as symbols --
some by some reason preserved, surely untold many more lost forever)
geographical structures

timeline: appx 1950
at this point, there was a schism. one group took the stance of the ardent
philosopher. there is clearly something much deeper in the connection between
magic and mankind, and we must find out what it is. it could be dangerous, or it
could just be something that will revolutionize our lives and our understanding
of magic. either way, we need to figure it out.

the other group smelled a trap. they argued that humans had been using magic for
hundreds of years -- perhaps thousands if these clues were true -- without any
kind of noticeable backlash. who knows what would lie at the end of this puzzle?
some maddeningly shiny technique that when used would destroy humanity?
something that would cut us off from the magical source? all this prophecy is
very much a sleeping bear.

and so they split off. and not cleanly either -- both groups thinking that the
other was wantonly throwing the fate of the human race in the trash led to a
complete severing of ties along with plenty of deaths, backstabbings, and
betrayals. this was a messy divorce. the first group became the group referred
to as $group2 (ascetics). they fervently hunted the trail of the puzzle, and
over the next hundred years actually made quite fair progress putting together
all of the pieces (see: section 'group 2' for a list of things they know at the
time of the story). the second group decided to consolidate their power into an
entity that could control the world, and they decided on the united states of
america. this is the group referred to as 'the government'. 

there was also a third group, a sect of those who wished to solve the puzzle but
did not think that stopping magic was the way to do it. this is $group1,
ironically. they decided that if the puzzle was this ingrained in reality,
whatever was coming for them was like a freight train at this
point. unstoppable. coming no matter what you did. and they were a 'die on your
feet, not on your knees' kind of people. so they dedicated themselves to
studying the art of battle dogma.

the government has far more resources, and has thus been able to dedicate entire
warehouses full of people to working on cracking dogmatic secrets nonstop. it is
a massive industry, and because of this they are quite advanced as
dogmatics. group 2 have also been able to keep pace, however, with the help of
the (rather substantial) amounts of magical knowledge hidden within the puzzle
they were solving. part of this magic is defensive or evasive magic, which has
made group 2 nigh impossible to snuff out in the intervening period.

$group1 has neither of these things (massive resources or ancient dogmatic
knowledge). for this reason, they have remained mostly underground -- at times
not even really existing, just clinging together. but what they lack in
resources they make up for in spirit. 

the fighters believe faithfully in their cause -- even if the smaller numbers
means that their odds are longer. 

** $group1 (fighters)
those felt they were powerful to attack the government head on in force. they
have many powerful dogmatics trained in battle. at this point, boon asks what they
mean by battle. they explain that there are strange magical beasts that can be
summoned and controlled (with great effort) by those trained. this first group
uses these beasts to attack government outposts and seize government
assets. however, they've realized that they weren't as strong as they'd
thought. they cannot directly attack the government or attempt a coup. they
would be destroyed if they tried. in the two years since, they have settled for
being a thorn in the side of the government. they have suffered many losses and
have seen many friends and family die. they are extremely hardened and bitter,
especially at the lack of support from their once-brothers.
** $group2 (ascetics)
the second group kind of resembles religious ascetics. they see what magic has
wrought. they see all of the inequality, exploitation, and they reject it. their
goal is to destroy magic. they learn all they can of magic so as to better see
it when it is use, to better know how to destroy it. they seek the abolition of
anything magical. nothing personal with the government. they see the government
as less of an evil thing and more of an unthinking malevolent thing. moreover,
they are doomsdayers. they believe that if humans continue to use magic, the
race will cease to exist.

moreover, this group has a very interesting quality: they have pieced together a
fairly good idea of the fall of man and the prophecies that were laid
thereafter. they know, for example:
- there was an ancient race of highly advanced dogmatics
- they faced an earth shattering conflict which wiped magic from human knowledge
  for thousands of years
- the conflict was caused by the use of magic and will one day return
- a vague idea of decision points and multiple timelines, though no idea of
  their mechanics or how to enter/manipulate them
- "a powerful one imbued with the spirit of an outsider" will return, and the
  fate of humanity lies with them

it's real easy to make this group unrelatable. just a bunch of nuts, or just
people who only have one dimension to them.

** boon
- traits:
  - someone who's just stumbled into this mess
  - likes to roll the dice, likes to skirt on the edge of danger
  - deep trust in your gut
- themes:
  - gaining a heartfelt faith in yourself
  - the vigor of an intense adolescent
  - placing your identity in a community
- motivations:
  - understand the place of his life when there are things so foreign in the
    world

boon is nobody before we start. a magical lad with a seed growing inside
him. one day it breaks out of its shell and distorts the world around him, and
he himself. he begins as a shy boy, unsure of who to trust or how to understand
anything that is happening to him. but as knowledge and power flood into him, he
becomes wild. he becomes manic with the understanding he is gaining of the world
around him, his faith in his abilities, reckless.

I like a character who, meek and timid, has power thrown at them and becomes a
strong and firm leader. I like people who take their lives into their own
hands. Boon is someone who realizes that it's possible to do that. There will be
events where he gradually realizes he is powerful enough to do it. He will grow
less timid and afraid. Where are these things gonna happen?

- In the basement, he's basically a frightened rabbit
- With the police chief, he feels overwhelmed -- he has just killed a man for
  someone he hardly knows, he realizes that he is not defenseless but doesn't
  know what to make of this
- At the beginning of the next scene, nothing has changed. He's still a worker
  bee. He's going along with this because he has no other option and feels
  lost.
- In the forest, he feels the darkness all around him, and self-doubt and
  existential crisis enter (what am I even doing?). He feels a lack of agency
  that is sharp and startling and unlike any pull he has felt before. This
  frightens him.
- After defeating the forsaken, he realizes that he is more powerful than he
  thought. But he is beginning to realize that his power also comes with a loss
  of self-determination, and that there may be something unseen pulling at his
  strings. His power means that he is not afraid to act, but he is too
  overwhelmed to take charge of anything. 
- The tunnel is rock bottom. He's just learned that not only is the fourth
  dimensional conspiracy real, but the government is also involved. The fact
  that they are kind of fighting on his side is irrelevant -- imagine that
  aliens invaded the Earth in utter secret, and once you killed one you discover
  that the entire force of the US government was battling them and was still not
  enough. He knows that he is strong enough to take on one of them, but he has
  no idea if that was the runt of the litter, or if they could all come after
  him at once. His death, or that of the human race, could come at any time.
- The talk at the camp gives him some spirit. The people who are in this with
  him telling him that he's the 'right man for the job' gives him faith. He also
  makes the decision to go into the desert (a sign that he has some confidence)
- After defeating Hegdesius, he understands that whatever the threat is, there
  is something about him to where he has enough power to do something about it
- When he returns to the camp, he realizes that if he doesn't take control, no
  one will. The fact that many people stayed behind to follow him empowers
  him. At this point, he's still walking on eggshells and needing support, but
  understands the role he'll have to take. 

** L. Roth Bethlehem
L. Roth Bethlehem is not the leader of the government in name, but is
unquestionably its leader in all other regards. He is a dark man. Looking into
his eyes will strike fear into any sane man. He is the most powerful dogmatic
alive. He began life as a street urchin. at the tender age of 10, he was pulled
from the streets to begin a life of government service. he has a prodigal talent
for manipulating people, born from his life on streets. he also has an
unbreakable will. at 20, he began reading heavily into the government's library
of documents. he found a store of documents, photocopies of ancient scrolls,
that hadn't been touched in seemingly a hundred years. these papers were the
beginning of humanity piecing together the mystery of the ancients. all of the
information was know, but it was so cryptic and seemingly innocuous that no one
paid it mind as more than ancient religious prophecies that happened to be found
in strange places.

he spent three years piecing together the mystery. at this point, he was one of
the five most powerful dogmatics in the world. understanding the prophecies of the
ancient people changed him. the works also contained a few scraps of powerful
magical secrets, which he also completed.

one night, while working out one such scrap, he faltered. he accidentally
channeled too much power. he entered a psychedelic daze. he spent eons in his
mind, trapped, seeing visions of branches of the future and past. he saw the
true history of the ancients, and the true meaning of the prophecies, as clear
as glass. in the visions, he saw incredible suffering of every human
alive. slaves for all eternity. he also saw smaller visions -- himself being
crucified, himself being sacrificed for nothing more than a little money and
power, his soul exiting his body and intertwining with great magical forces, a
million men standing before him weeping.

he left the visions a changed man. the true pain that could be inflicted on a
human was now branded into him. he knew there was only one way to prevent it:
complete authoritarian control of the entire human race as part of one massive
war effort.

that was 40 years ago. bethlehem is now almost 65. he is slightly frailer than
he once was. his mindset has deteriorated in the past decades. the visions were
so strong and so formative that he has obsessed over them. they are his only
purpose. those going against his wishes are executed. he has taken duty to its
most extreme.

his means of doing so is the giant sa'angreal that he has unearthed outside the
city limits.
** tess
- traits
  - someone who can be overwhelmed with force of personality
  - someone who looks up to people who have agency over their lives
  - someone who feels like a robot because their life must be spent fulfilling duty
  - someone who is very powerful and knowledgable
- themes
  - whenever you gain power, your life becomes a little bit less your own
  - not everyone gets to feel simple human pleasures and have intense emotional
    moments
- motivations
  - live vicariously through other people
  - maintain her facade
  - find a way to experience joy and express herself

she is a member of $group2.

she is a woman with fair skin, dark hair, and deep-set sad eyes. she is one of
the oldest (not in age, but in years served) of the ascetics. the knowledge of
the doom that will fall weighs very heavily on her, and she desperately wants to
follow instead of lead. she knows, though, that she is the only person who could
do what she does, and it would be impossible for her to follow.

she is only 30, but she's very powerful. she had just finished high school when
she was overcome by the test. she obviously passed, but her life was wrought
from her. luckily, someone in her family was secretly a dogmatic, and a
dissenter at that. he took her in and unveiled the curtain for her. before long,
it was clear that she was an extremely powerful dogmatic.

a few years after she'd entered group 2, her direct mentor and leader of half of
the group was killed in an internal power struggle. she was the only person fit
enough to take over in the manpower-starved group. she was 21 and deeply afraid
of not being able to handle the job. her coping mechanism was to assert firm,
unquestioning authority whenever she gave orders or asked questions. after a
short time of this, it became the status quo. her agents under her knew they
would not enjoy defying her, and her natural brilliance made it so that you
probably wouldn't want to anyway.

she always wanted to understand the people fighting under her, but with the
group in such deep turmoil, she had no choice but to be a disciplining parent.

- ROLE IN THE PLOT:
she 'befriends' boon once he comes into contact with her group. he's an ideal
for her. he sees the stakes and he knows some will die but he has confidence in
his ability to fix the problem. he has utmost faith in himself and his
gut. these are the traits that she lacks -- he sees his duty as an extension of
himself, she sees it as a burden on her back.

she'll eventually turn on theseus and $group2. something about the beauty of
watching a person take on a mountain of responsibility with pleasure, retaining
their self and their agency when in a situation that requires them to submit all
of their self. that makes her realize that there's never just one way to do
something, you have power in your own life. 

- BACKSTORY & PERSONALITY
her demeanor is very flat, robotic.

she's never had a significant other. sometimes when she's in bed at night, she
thinks about someone being next to her.

she is almost impossible to anger

she finds it too painful to think of her sweet parents, but every once in a
while she will think about them and she will cry.

she's never had a real best friend, never had girl time, never been able to
confide in anyone else what she was thinking or how she felt.

she still holds much passion for the revolution. she knows this is a cause
that's worth sacrificing her life for, she finds all of the prophecy puzzling
and reconnaisaince and studying the fine art of magic fascinating. she loves the
people who she commands, she thinks they are brave and admirable. but that
doesn't mean she can't hate her life.
** sewell
- traits:
  - someone who's very happy go lucky (peco)
  - someone who sees the best in people
- themes:
  - if humans win against the ancients, and entire species will be
    exterminated. is this what a good person would do?
  - lifting the veil would fundamentally change the way people live. is it his
    decision to make, and what if it turns out poorly?
  - what if life after the veil is worse than before?
- motivations:
  - help people immediately, even if it ruins your long-term goals. no trolley
    problem here!
  - people around you need your support to be their best selves.

sewell is a happy-go-lucky big man. he knows everyone's life is probably going
to be short, but he feels like he is making a difference and that makes him
happy. he used to work as a low level conjurer for the government, but he
defected because of the brutality against the people.

sewell is constantly blasted with things to make him cynical. he watches a group
that he's invested his soul into do horrible things to people. he watches as his
friends and comrades grow weary and evil with their power & burden. he lives in
a world where the path to happiness for all seems bleak. and he remains happy.

that's not to say that he is gullible, oblivious, stupid, or corny. he very much
understands all of the terrible things that are happening to people. they make
him feel bad. but for sewell, these things just reinforce his purpose as a do-er
of good.

he also faces things that he personally does or is involved in that are not
good. he even has to kill people in cold blood. but he knows that he is still a
good person because these things make him feel hurt. he doesn't try to do bad
things, and he deeply believes that even good people do bad things quite often.

he is also a very supportive person. he realized early on after joining that
there were a lot of bitterly angry people there, there were people who wanted to
spite and make others hurt as they did. with a lot of hard work, he managed to
turn the revolution from a white-hot forge of anger, heat, passion, into
something that more resembled a community.

kind of reminds me of bosley. on the outside, a bit threatening. on the inside,
sharp as a whip and kind as could be.
** evans
- traits
  - someone who is good, but bitter and deeply nihilistic
  - someone who hates magic but does it because they are good at it
  - someone who feels a mountain of duty
  - someone who is a stone faced protector
- themes:
  - your bitterness is justified
  - people who work for a good cause may be bad
  - helplessness
- motivations
  - other people must be protected regardless of cost to self
  - goaded not by anger, but by unfairness
  - most people are helpless, machines, and must be given leeway as such

evans is like a mentor to boon. he is older, he is tougher and less naive, and
he is smart as a whip. he has a hard outer shell. but he will never do anything
that results in harm to someone who he is close to or pities. 
** theseus
- traits:
  - someone who is self-serving
  - someone who is cunning
  - someone who is cruel, but not needlessly
- themes:
- motivations:
  - dominate the post-apocalyptic world & rebuild it in his image
  - lash out at other group 2 members for poor treatment

let's start with theseus. first thing that comes to mind is draco malfoy, but i
really have no idea who draco malfoy is as a human. i think he has a redemption
arc or something. but i can't be sure of that. theseus is one of those people
who you both hate and admire at the same time. someone who is extremely clever
and knows they are clever. someone who doesn't let anything get in the way of
what they want, but worst of all, never fails to cover his tracks and never
leaves anything incriminating or gamebreaking. in one word: confidence. started
off as a child prodigy, kind of like that guy who is a doctor a lawyer and an
astronaut all at the same time. with some prodigies it's like they sit down and
focus and study on what they do and they understand that one thing very well,
but that's not how theseus is. theseus understood everything, and his particular
focus wasn't something that you can sit down and study because he was very good
at manipulating people. part of his skill comes from the fact that people think
he is skillful. one of those things where he has a reputation and people make it
so. he has slicked back platinum hair not unlike a young draco malfoy. he's a
little like adam in that when he comes by you straighten your back and start
polishing something and don't ever say no. but that's kind of the part you hate,
the worst part is that he can be utterly charming too. like you see this guy who
is brilliant and successful and powerful and he talks to you like you're his
equal. he talks like his ideas are your ideas and seemingly gives you respect. 

trying to think of something that theseus would say
"absolutely my friend, but surely you see my side of this is quite precarious as
well?" -- i don't think he would say that, usually calling someone 'my friend'
is being a bit too obvious with your manipulation. 

NOT something like fatherly "well, of course you'll do as i ask, won't you?"
because he is not the type of cunning that relies on his power to be cunning,
and saying something like that is thinly veiled intimidation

the fact that he himself has infiltrated the government, sits sitting a cocktail
as you come in, leaves you a powerful angreal -- the fact that all these pieces
slotted into place and he's just sitting there with a smile on his face telling
you that you'd like to hear what he has to say. now THAT is theseus. 

"well hello there. it seems i've been waiting a long time for you. if you'd come
with me, i have quite a few things i think you'd like to hear."

"because either you would use it or be destroyed by it"

"everything that's happening now can be stopped. you yourself hold a rather
precarious position in this matter."

"well, either we cut every human being from the dogma and go back to
mesopotamia, or we try to fight back"

"are you with me or against me?"

he speaks in false dichotomies that are impossible to disagree with. if you call
him out on them he explains precisely why the dichotomy is true, all the while
ferreting you into understanding why his position is correct. arguing with him
is insufferable because his arguments have no holes. he does not concede. he may
not bully you with threat or power, but he will bully you nonetheless. 

and his ultimate goal as a charmer, as someone who is addicted to power, is to
rule the world. he plans to do this by tricking everyone into linking their
power to somehow sever reality from the magical dimension whilst still retaining
his power. and it's hard to say that he's a bad guy either, because he will
argue every single one of his reasons for doing so until you completely succumb
and declare him your god emperor before his plan has even started! his reasons
make sense. humans have two options, as it stands. either return to a life of
quasi nomadic farmers at the mercy of nature and thousands and thousands of
years of suffering ahead of them. or fight a race of interdimensional beings who
have been practicing the magical art for aeons and likely be exterminated in the
process. he, through all the breadcrumbs, has discovered a magical method that
-- and note that this is untested --- he thinks will essentially rotate the
aether of existence such that the plane that humans exist on is entrance
only. by doing this, the current of magic can still flow through, but any
magical entities that wish to destroy the human race would be trapped here for
eternity. tough sell for any would be pikemen. and this isn't a one time thing
-- this is a thing that requires some amount of upkeep. and so naturally,
theseus would be the one doing so, and would require vast amounts of dogmatic
power. he would hold all dogma through the channel point which it flows into our
reality and disperse it throughout society.
** ike
ike is the leader of $group1. 

ike is a good-spirited mechanic in spirit. he's gruff, he's a bit old-fashioned,
but at the end of the day he's got a good heart. he absolutely empathizes with
boon, but he's not one to show his empathy through words of comfort or
affirmation. he's the kind of guy where the fact that he cares enough to
apologize or offer any gruff words of encouragement is equivalent to another man
giving a long heartfelt speech. 
* act one
** intro
boon is sitting in his living room. his phone rings. it's his dad, and he asks
him if boon can go to ike's the hardware store a bit across town before he comes
home. he needs a few special screwdrivers so he can fix boon's computer when he
gets home. boon sets out.

after a while, a man comes and taps boon on the shoulder. he whispers in his
ear that he is in incredible danger, and that he must come with him if he wants
to live past this day. boon and escorter walk back to the enclave.

you reach the basement. there, the man breathlessly asks boon what the hell he
was doing. he says that boon was broadcasting dogmatic signals so far that
anyone remotely sensitive would have been drawn to him. magic exists. the
government is run, from the top down, by dogmatics. all of technology is just the
manipulation of powerful magical energy which resides all around us. the
government has this on complete lock down, and they do not take kindly to
wilders. they have many, many ways of tracking down kids when their powers start
to emerge. they're usually lock tight, and the guy has no idea how boon could
have lived this long undetected while being so innately powerful. 

they explain about the revolution.
the schism, three groups, their aims (see: backstory).

they explain about the _government_.
their fascist streak runs back to when LRB first took serious power in the
government, around 40 years ago. LRB is not officially the president, and in
fact people who are not interested in politics may not even know his name. their
ruthlessness is, according to people on the inside, necessary to keep the use of
magic a secret from the general population. people say that LRB is an
unimaginably powerful dogmatic, and that perhaps half of the world's magical power
stems from him and/or magical systems that only he could set up.

after the history lesson, they bring boon into a back room. they can feel the
spark of battle in him, and they're going to test him to see if you can use
it. the examiner asks him to close your eyes and focus intensely on their
presence in the room. the screen goes black. images begin to flash in and out,
distorted. a fractal. a screaming beast. the face of a creature with an eye on
its forehead. mouth open, going into the mouth, a bright light appears then
consumes everything. boon opens his eyes. the examiner smiles and says, yes, i
think you'll do quite well. he explains the battle system, and begins the rites
of taming three magical beasts. 

boon is invited to go around and talk to a few people to learn a bit more.

after talking for a while, they hear what sounds like a battering ram on the
door. the man hurriedly tells boon to go to Ike's Hardware and Supply Depot. go
there, find ike, tell him that one of your wrenches has been acting funny. 
** the hardware store
boon goes there and is greeted
warily by ike. ike's gruff with him. he takes boon to the back room and
immediately starts a battle with him. ike is a reasonable match for boon, and
when boon wins, he gives a laugh and claps him on the shoulder. "so you're the
real deal, eh?". he apologizes, saying he just had to check to make sure boon
was with the people he implied he was when he used the secret phrase. it's just
business. 

ike asks what boon's doing here. he says that he leads a band of revs who camp
in the forest outside town, but he (like everyone) has to come back often to
keep up appearances. it's dangerous to send a dogmatic to contact another who is
keeping cover, so he says he hopes it's important. boon relays his
situation. ike, in his gruff way, gives him sympathy and says that boon's
position is not an easy one.  

he says that they need to get boon to their camp outside town. it has far more
wards than what are here, they will be safer there, and boon can learn more
about what's going on. ike says that they'll need to take a more roundabout path
to hopefully throw the police off their scent. there's one place that they
usually won't follow them, and it'll lead them straight into the forest. the
reason they won't go there, though, is because it's kind of a dogmatic mess. the
same beasts that boon can control have started manifesting themselves in
reality, and the place that they're going is a hotbed for bands of them. 

boon has no choice but to go. 
** taking the backroads
ike hurriedly leads boon through the city until they reach an alleyway. the
alley ends in a fence that seems to lead to just trees. ike beckons boon forward
and they go through the fence. 

@dungeon
they're in a dark undercanopy. ike asks boon if he'll be okay doing some
battling. boon affirms, and they walk through. this dungeon will have a few
low-level bands of monsters (1-3 per band). nothing too strong, no
puzzles. there'll be an item here so you can figure out how to use those. 

near the end of the dungeon, there'll be a boss battle. ike trips over a root,
and out from the forest comes a dark, specter-looking creature. it tries to grab
boon. ike yells at him to fight, damnit, and you nervously plunge into battle. 

once you defeat it, ike seems impressed. he says no one he know has ever picked
up on battling that quickly. he says that you're going to come with him to see
some of the rev's brass. 
** brass tacks
when you come to the camp, you're greeted by:
sewell
evans
tess
theseus

first, they assure you that you're no longer in danger. they half-heartedly
scold ike for bringing boon on such a dangerous route, but are similarly
impressed that he managed to handle himself so well. they mention that a few of
their numbers who were unprepared have managed to get themselves killed out
there. 

they tell boon: i guess there wasn't much time to explain before, but now's a
good of a time as any. the government has been acting extremely strangely
recently. normally, we kind of exist in a peacefully antagonistic
equilibrium. we don't like how the government monopolizes the use of our
natural, inborn powers, but on the whole we understand that there's nothing we
can really do with our current numbers. and the government has enough on their
plate that dealing with us is not a high priority. 

but lately...they've been acting strange. they've been sending out scouting
groups to remote, hostile locations. they've been peddling around armored trucks
that seem to be full of nothing. they have been seemingly randomly detaining
people for indefinite periods of time. we know something's up with them, and
we've been trying to figure it out. wanna help?

the first mission: strange things have been happening in the forest of
late. first off, there's the backroad that you took in here. that didn't used to
be so infested with hostile beasts. and that infection has been slowly
spreading, to the point where the wards on this camp haven't been completely
effective. it's really bad a little deeper into the forest. 

the weird thing, though, is that while the cops are skittish about taking the
back roads, there's been a ton of government activity at the deeper, more
dangerous part. something is up, and we're going to investigate. you'll be going
with evans. hit the hay before you head out -- you should also check out the
apothecary and the items shop. we let people collect magical booty and do as
they wish with it, including selling it. some of it's good stuff, if you got
coin. 

before you go, tess wards you. they say that this ward should make you magically
uninteresting for the indefinite future -- people trying to detect you magically
won't be able to until it wears off. she says, though, that it won't be safe to
return to town until the ward has fully seeped in. a few days. 
** deeper into the forest
it's a stormy night. everyone agrees that something feels a little off. when
everyone gets to the entrance of the forest, evans gives them their
commands. they're going to split up to keep up the stealth. boon will go with
evans. 

after everyone leaves, evans turns to boon. he tells them the plan: the path
they are taking forks immediately. evans will go right -- that path brushes
right up the government encampment. boon will go left, but be careful, because
it's still bound to be a hotbed. you'll probably have to take out some
baddies. don't make it too loud. at the end, both paths rejoin in front of an
overgrown stone altar. wait for evans there. 

@detail: the altar -- what does it say? symbolism (deer?)
boon goes through the forest. at the end, he reaches the altar. evans appears
from behind. he says he wasn't able to find out much from the encampment,
besides the fact that it's hotter than he thought. what he did notice: all the
tracks lead to a basin that is a bit deeper in the forest. he knows these paths
well, and he know how to get to the basin from where they are. he tells boon to
follow him. 

after reaching the path that should lead to the basin, they realize that it
forks. evans kneels down and inspects the forks. he says that it's impossible,
that these paths are ancient, moss-covered, like they have been here for fifty
years. he says that something seriously spooky is going on. they have to go
further and check out what it is.

the world becomes darker and more twisted as they travel. the sky darkens. there
are animal skulls pinned to trees. evans almost falls into a tarpit that
materializes from nowhere. conversations, like a cocktail party, fade in and
out of the background. and there are beasts here. there is a miniboss here. 

at the end of this dark path you come upon a shining cream-colored palace. it is
perfectly kempt -- beautiful hedges and flowers adorn the outside, the marble
steps gleam to perfection. yet the world flickers and distorts as you approach
it. 

you approach the door of the castle and hear a conversation grow louder. it is a
man, with an old voice, like bill. @note: no actual voice acting, that's just
how i imagine him. from kill bill, for those interested readers. he says that
work is progressing just fine, but he must ask again: why can they not simply
unlock it for him? at this moment you peer between the slats of the door. evans
nearly cries out in surprise: it's LRB! and he seems to be cavorting with
something that is there and not at the same time.

another voice appears, gravelly and guttural, barely human. it asks him why he
doesn't turn his grandfather into a computer programmer. i have no control over
that, says the first voice, my grandfather has already lived and died. and so,
too, is why i cannot open the sa'angreal for you. know that i have done what i
can, and do not ask again lest you invoke my wrath.

* act two
** what just happened?
the three meet up once again. sewell and evans are shocked at how powerful boon
has gotten. they talk about what happened to then. 
@detail
sewell feels:

evans feels:

boon feels: 
in over his head
important
like a puppet in a play
can't understand the changes to himself
weak for being afraid
good about the revolution (?)

(basic points)
sewell: they're abusing everyday people. they're playing with them like animals
to further their goals. i didn't realize what was going on when i joined, i
thought we were just messing around with some government servers.
$group1leader: nothing worse than what the government does every day. and besides, what
do you think those servers power? you think no one ever skipped a meal because
of your actions?
sewell: ...

evans: they're sending kids out to try to kill guards. they're indoctrinating
them. most people can't protect themselves, but kids least of all.
$group1leader: do you have proof?
evans: not that they're sending them out, but i saw two indoctrinated lads with
my own eyes
$group1leader: kids younger than them made bigger decisions throughout history. the cause
is just. i don't like to see them die any more than you, but that's their
prerogative.

the conversation ends with considerable tension between the three. $group1leader ends it
by telling them that there is a government unveiling of a massive construction
project. boon walked within a mile of the site a few days ago and felt a ripple
in the power. there is something fishy. plus, he heard that LRB will be there to
speak personally.

$group1leader tells them to go talk to the bedkeeper to get somewhere to sleep, then come
back to him the next day.

as boon walks away, he gets a flash. it is brief -- kind of an idyllic pastoral
society. he can walk around, talk to people. they greet him as a good
friend. they offer him tea and stew. he walks up to a dark man who appears out
of place. the man begins to sputter nonsense, angry, surprised, until boon runs
away. he falls, and he flashes back into reality. 

@sidequests
** the announcement
once they come back and talk to boon, they black out and back in near the
construction place. it's right out side of the city limits, on the north
side. they've billed this as an announcement that is going to change the way
that people live their lives, it's been plastered over the news. there are a lot
of people here. everyone is a bit excited, a bit nervous.

LRB walks on to the stage as his theme plays. the crowd silences as he walks
onto the stage. he announces that government researchers have been slavishly
researching a new kind of technology. recently, they've made a
breakthrough. they've discovered a class of weapons that will make america
unilaterally the most powerful nation on earth. he brings out a poor lad. he
takes out a spray bottle and sprays in the man's vicinity. the man immediately
begins screaming, writhing around, tearing at his face, tearing at his throat,
begging to die.

LRB calmly steps up to the podium and speaks. weapons that cause this level of
pain have existed before, but not at /scale/. we can employ this weapon so that
every person in a one hundred mile radius will behave exactly as this man until
they die in appx. 72 hours from dehydration. this weapon could be easily
deployed to every major city in the nation. production units already exist.

he says that the city will be converted into a massive factory. they will expand
the city to five times its current size, with all of the space being used for
weapons manufacturing and all of the citizens as loyal employees. effective next
week.

everyone is in shock. LRB excuses himself. sewell, boon, and evans quickly talk
amongst themselves. they all feel the ripple in the power. they know that the
weapon he is talking about is magical in nature. they feel urgency, and they
decide to explore the area more while everyone is in a commotion.

they see LRB walking in a direction, then down a set of stairs carved into the
ground. there's a guard there. they talk past him or kill him and walk down into
a tunnel. the tunnel is LRB's personal escape bunker -- partially a bug out box
and partially a place to relax.

** the tunnel
@dungeon
the tunnel has guards, but it's not swarming with them. in the tunnel are
several places to explore: a library of books on ancient history, political
theory. a room of strange magical fixtures. a private office containing LRB's
some of these rooms have wards. you must find an air vent to spy on his
room. @detail should make this into a heavier dungeon
magical experimentation room
LRB's diary + library with books of interest
a warded room which spawns "ghost" trainers

once you get to the end, you see LRB with a few guards and a few important
looking people. the air is somber. LRB is sitting in a fine chair and others are
standing. one man who is standing angrily tells LRB how he promised there
wouldn't be any more violence like this. not against their own. LRB is silent,
and the other man keeps talking.

after a moment, LRB stands up. the man stops talking. guards begin to shuffle
away. LRB has a short monologue about unflinching authority. he kills the man,
and all is silent. he bades everyone leave, and as they are leaving he calls his
son to stay. his son is his one confidant. bred specifically to be magical, and
only exists so that LRB has someone to pass on this mantle of extreme importance
to. they are silent for a moment.

- strange moment of clarity regarding his ruthlessness
- time is growing short
- in some capacity, he is aware of boon's existence
- the search for the sa'angreal is going well, and LRB is sure that this is the
  one that is propesized
- the forsaken grow closer -- he felt two of them wink out of existence, but
  four more exist. one, like a god king, has retreated to the magical plane
  after the death of two of its subordinates. the other three are here figuring
  out what happened and moving their plan forward. he senses one of them in this
  very city -- sometimes, it feels intensely close (this is boon).
  - the four:
	- desert
	- the crazy one
	- god-king
	- boon
- one of the forsaken is out in a mirage palace in the desert. LRB has felt the
  other ones, sometimes in partial existence, sometimes only for a few days or
  moments.

** consolidate
after this conversation, they leave, and everyone returns to the base. they have
a conversation that consolidates some knowledge and viewpoints.
- there are forsaken coming to destroy humanity
- LRB knows about them and has kept it from everybody, including seemingly the
  government itself
- there is a massive channeling tool that is LRB's hope to defeat them
- boon needs a cheering up @detail from who? need to flesh out sewell/evans more
  before I plan this conversation. 
- $group1leader thinks that LRB probably wants to become an omnipotent ruler by
  means of harnessing some dark dark magic
- sewell + evans aren't entirely convinced, but believe it's plausible. they
  also float the idea that maybe they have to /help/ LRB or face the extinction
  of man
- further disgust at the government for the murder
- chosen one? they mostly realize that this must be boon
- we shouldn't tell everyone else about the sa'angreal

they decide that they have to go investigate the desert, no matter the
danger. they don't know exactly where it is or how to activate the mirage, so
they go looking for clues on how to get there. evans knows a man who runs a
hustle in the desert. he looks for sand patches that get blown around to uncover
sand that is perfect for glassmaking. if anyone would know anything, it'd be
him. his name is barr.

@sidequests
** the desert
(THIS CHAPTER IS AWESOME)

the group travels out to the edge of the desert, where barr has a few tents and
dune buggies set up. he's dressed kind of like hunter s thompson, he's smoking a
cigarette. he claps evans on the shoulder like they're old buddies, says how
evans helped him out of a serious jam years back. they ask him how business has
been -- he says bad, real bad. people keep disappearing. it started with his
friend Cyg, a kind of feisty raider girl who always rode into the desert with a
shoufa, a gun, and plenty of supplies. not like her to get lost like this. he
can't hire out anyone to go because it's practically a death wish, and he won't
do it himself.

they tell barr that they'll pay him a large sum of money to escort them out. he
looks at them like they're crazy and tries to convince them not to, but in the
end finally relents. they tell him that they are looking for a castle in the
middle of the desert. he's taken a bit aback, because he's seen flashes of a
castle out of the corner of his eyes that match their description. he says it
started happening right before people started disappearing, and that it's always
in this one quarter mile radius of the desert.

they drive out there, talking on the way @detail. the dune buggy shudders, the
screen glitches a bit, and all of a sudden they're standing in a dimly lit
basement. boon somehow understands that they are in another world. they explore
for a bit and solve a few puzzles, and boon comes to a shining place on the
ground. he says that he knows that this will transport them back to their
world. he uses it, and the four of them are brought to a portal stone right
outside of the castle.

@dungeon
they work through the castle and the house, solving puzzles. in a room
in the house, they find the people who were lost. he sees cyg and calls out to
her, but she doesn't respond. no one else says a word. without warning, you
begin battling her. once defeated, everyone else runs over to you. they tell you
that when they fell into this building, cyg was already here. she had food but
it looked untouched. all she would do was ramble about the sins of man and the
return of the righteous. she didn't eat or drink for days.

@detail
ideas for puzzles:
promesst-style; mirrors, beams of light
(simple) switches which

as they reach the final hallway / heart of the castle, things begin to glitch
more and more. they are transported, for a few moments, to many places. a
pastoral town where someone cries out in terror at them. the smoldering ruins of
a city. an mountain pass in the midst of a blizzard. all these places flash in
for just a few moments, and then they are gone.

finally, they reach the room of the forsaken.
an office
more strange contraptions
a platform of battle

they begin to speak. conversation notes:
- he says that boon feels familiar, and that he can feel the ripples he makes in
  the magical world. he knows he is powerful because he made it to him
- a bit sad for having to wage war
- amused that the humans do not know it
- "hmm...what would be a fitting name in your language? something appropriately
  ancient, something a bit frightening, something powerful. for i am all of
  these things, you may call me hegdesius."
- he does not know that boon has the spirit of a fallen kin in him
- tells them about decision points & split timelines
- there is much history between your people and mine. he does not tell boon the
  full story, but he says he's observed a very strange group of people who seem
  to have a handle on the truth of the matter (group 2)


they battle. as you land the death blow, hegdesius is in shock. it is babbling
the way you would when you learned you had let your entire race down. he regrets
he does not have time to warn the others, but he hopes they will be able to
sense the three deaths though distant they are.

everyone returns to the camp in the forest.
** while you were away
@detail more memorable characters at the base
@pacing there isn't a lot of gameplay in these next three scenes

when they return to the base, everyone seems shocked to see them. they tell them
that the group has been gone for ten days. once people realized that the
government was serious about going full on war mode, tensions between all
parties escalated. the populace is agitated, but are getting fed and
paid. altogether life is normal, and most signs point to the government treating
people humanely. nothing has been heard from most of the hackers -- they are all
assumed either MIA or dead. those in group 1 who are still fervently for attack
have begun splintering off, running raids on government construction projects,
demolishing construction and killing guards and civilians in the process. those
who have remained have decided one thing: they must follow boon.

and group 2. group 2 has been especially problematic. they have begun slaying
magic wielders essentially at random. word has it that they believe there is no
longer any more time to bide. they speak of strange things that have the ring of
prophecies -- decision points, the breaking of mankind, a powerful one imbued
with the spirit of an outsider. they seek this one, say that if the prophecies
are wrong or if the one is dead then all hope is lost. this is the extent to
which they have communicated with the other factions.

the government, too, has done its part to lash out. there have been an
unprecedented number of raids on all kinds of places -- basement hideouts,
server racks, remote camps, etc. this camp has gone undetected because of the
bad reputation of the forest. hundreds of revolutionaries have died in the past
week. families of the killed and captured have gone missing, families of
defectors as well. even though they haven't split off yet, everyone still
remaining feels that they are coming to a critical point in the revolution, and
that something has to be done. they need boon to make a plan.

boon says that they should go talk to group 2, see if they can wrangle their
support against a common foe and deal with their murderous tendencies
later. someone at the camp replies (@detail who? no nameless soldiers) that,
well, this is a bit awkward, but we were hoping you wouldn't say that. see, a
few days ago a lone messenger came to their camp and dropped off a message.

@detail
it is a small scrap of prophecy.
not really sure what i want it to say. not something too corny. want to stay
away from words like 'the chosen one' and 'the keepers'. anyway, the prophecy
says that they know that boon must be alive or everything is fucked.
the prophecy given by group 2 alludes to a prophetic hint that the groop
received at the castle

they tell you to go to a hole in the wall restaurant and ask for a table under
the name 'troy'

** the restaurant
boon, sewell, and evans walk over to the restaurant. right outside, they see the
sun glint off of something and go to pick it up. it is a small figurine. when
they enter the restaurant, they tell the clerk the pass phrase. the clerk makes
an offhand comment -- never seen you around here, you don't look like the usual
type. but i was told someone by this name would be coming around.

when they walk in, they immediately realize that it's a trap. they see cops,
guards, officials everywhere. this is a magical hotbed, and the combined power
in there is enough to wipe the three of you off of the face of the planet. you
have no choice but to fight. but strangely, boon absolutely tears through
everyone. every attack is a one hit kill. after a single battle, everyone
remaining in the restaurant scrams, quick, except for one man.

they approach the man and speak to him. he seems cool, collected, and slick --
very slick. he does not come off as sinister, merely unsettling. you can tell
that he appreciates having the power in this (or any) situation. (this is theseus)

he says that he is a double agent for group 2 who functions inside the
government. the figurine that boon had is -- or was -- akin to an angreal. a
magnifier of power which, combined with his natural talents, made him more
powerful than anyone in the room could fathom. extremely rare. it was also a
relic, found wrapped in a scroll describing its use; only the one prophesized
would have the access to the dogma needed to use it. moreover, its use would be
like a chemical reaction with the one prophesized: a bright flash of heat and
smoke, and then its contribution would be spent.

boon is confused. he says that they have encountered things that sound similarly
prophetic, and in situations where he is inclined to believe them, but he has no
context.

the man smiles and says, i think we've been waiting for you for a long time.
he bades them come with him to learn about some things they will find very
interesting. he bades them over to his suitcase, which contains a square stone
glowing with a bright blue circle in the center. 
** hello, group 2
with a flash, they are in a building that looks like a laboratory. everything is
sleek light blue and silver, fluorescent, angular. it looks like a spaceship or
something out of westworld. the party freaks out a bit on entry and asks where
they hell they are. theseus replies, "about three miles under the surface of the
earth under, oh, let's say southern china".

everyone is shocked at this, even those who have been practicing the dogma for
decades. they argue about how it is possible. theseus says that this will make a
lot more sense if they let him explain what he brought them here for.

theseus goes on to reveal quite a bit about the origins of the revolution and
the knowledge that group 2 have discovered since the schism. he dispels some
rumors about group 2 (they only search books, they have no regard for reality)
and confirm others (they are actively and violently against the use of
magic).

--
don't want to plan this conversation out too rigidly or repeat what i've written
elsewhere -- group 2 genuinely believe that boon is the one they seek, they will
divulge all information to him excepting things they may find inconvenient
(which i will have to revisit when i sharpen up their motives).

tess is part of this conversation

conversation outline:
how could you kill your own kind?
they are not exactly our kind: [the schism]

how do you know this is true?
100+ years of research, specific pieces of prophecy. and speaking of prophecy,
there is something you may be very interested to know. you are an outsider, and
you have unimaginable potential -- more than any human who has ever lived. you
are "the one imbued with the spirit of an outsider". we're pretty sure the fate
of the human race is on your shoulders.
--

they tell boon that they want to take over the sa'angreal to link together
humanity to have a chance at taking out the forsaken. they believe that boon is
the only one with the proper power to wield it. they'd like his more ragtag
group of dogmatics to join them as a boots-on-the-ground force in taking the
sa'angreal. boon agrees. theseus tells him that he should return to america and
begin training his band of militants into something more resembling an
army. theseus also says that although everything must proceed with great
urgency, there are no concrete plans yet -- getting firsthand intel on the
government and training up an actually competent force is the most useful thing
that boon can do right now. 

before boon leaves, theseus pulls him aside and tells him to be very wary of
LRB. theseus says that he is no mere government shill -- even though most
everyone in the government can channel, LRB is on another level. until today, he
was the most powerful dogmatic known to $group2. he has locked away more
information on magic than most people will ever learn. 

he also gives boon a small angreal that will allow him to access the portal into
their base whenever. 

SPECULATION
he doesn't know that once they hold control of the sa'angreal, they'll try to
overpower boon and use his power to tap into things which are known to exist,
yet unknown in use. maybe:
still all of humanity (evil)
cut off our timeline from the greater thread (undefined behavior, probably evil)
use him as a da'mane of universal power and try to conquer reality

do they have a reason from keeping them from sharing this information with
$group1? one reason would be theseus' manipulative personality. 
** an uneasy toast
everyone returns to the base. evans approaches boon alone. he asks boon what he
makes of $group2 now that they're away from everyone. boon says he feels a bit
uneasy -- how they went about contacting him, the displays of grandeur and force
to show how powerful they are -- but he mostly trusts them. he thinks that if
they were any less aggressive, they could have caught a false prophet. and
moreover, this is a group of people who have dedicated their lives to piecing
together this puzzle and searching for a savior to take them home. evans asks
how many people you think died walking into that restaurant? he says that
theseus' confidence and influence make him uneasy. and he says that the woman is
hard, hard like she's seen some shit. 

evans asks boon what he's going to tell the rest of $group1. boon is surprised
at this question -- he thought it was implicit that he was going to tell them
all of it. evans lashes out a bit here. he says that they could never handle
that. he says that every last one of us is going to die in this war. at least
give them the dignity of thinking that they have a chance to live. (note: he
doesn't mean that he knows they will fail -- just that they will die). boon
agrees, and he says that he will reveal:
$group2 work in secrecy, and he can't reveal much about them besides the fact
that they are working with us now
the government factories are a front for harnessing the sa'angreal
we must be wary around the sa'angreal -- destroying it could have unknown
consequences. 
he is a man of prophecy

boon delivers the town hall. he saves the declaration of prophecy for last. when
he says it, everyone is silent. finally, ike steps up. he says something to the
effect of "well, lad. i knew there were something special about you. i don't
need to see nothin more to tell you that i'm with you until i keel over". at
this, there's a rousing scene. everyone feels some momentum and joy, this is the
first real "victory" for the revolution. scene fades out with people clapping
boon on the back, toasting, etc.
** one last brief aside...
@cutscene

cut out to tess and theseus. they are talking alone in a dim room. 
*theseus*: i can't believe he just came to us. it was almost too easy. tess, this
is the moments that our ancestors lived and died for. a hundred years of work
and blood and death in the hopes that one day we would live this moment and
execute their plan. 
*tess*:    is it really their plan that we're executing theseus?
*theseus*: no...but at this point, it's the only plan. the situation is far worse
than anyone realizes, including those government clowns. LRB is dangerous. 
*tess*:    do you ever regret this life, theseus?
*theseus*: no. sometimes the knowledge is like a mountain on me. but we both know
this is the only way that we can save humanity. anyway, the boy -- after all
this time, i somehow expected...more
*tess*:    we know nothing about him
*theseus*: we know that he's green
*tess*:    you must let him breathe. i can feel these things. the moment that he
walked in, i knew he was the one we sought. he is yet weak, but given time and
guidance, he'll be stronger than either of us could imagine. but the more you
try to mold him, the more he'll resist. 
*theseus*: i hope you're right tess...
* act three
** what happens after a toast?
this act opens up with boon someone waking up in his bed in the camp. he says
there's bad news, the government finally got the balls to raid the camp. they
did it in the middle of the night, and they didn't challenge anyone directly,
but they took most of the camp's food. they're not going to be able to hold out
past a week if they don't do something about it. the lad says ike, evans, and
sewell are waiting for boon in the meeting room.  

boon goes there and sewell and ike are arguing. evans is observing. sewell
thinks that they should go personally to accompany an attack force against the
government's thugs. ike says that would be foolhardy and they couldn't afford
any of them to go. sewell says they need our help now. boon listens to them
argue for a minute, coughs, and once they quiet down he says that he will go by
himself. he has a stronger magical sense than anyone, he could easily sneak
around and scope it out, and most importantly he's in charge. 

ike less acquiesces than realizes that he isn't going to win. once they leave,
evans pulls him aside. he tells boon that it actually is foolhardy to go alone,
but the only thing more foolish than one person would be more than one. he tells
him not to tell theseus that he did this. he tells boon before he leaves that a
couple people around camp have been looking for him, and that they might need
some help with a few things before he goes. 

as boon walks away, he gets a flash. the screen flickers frames of a scene,
until it stablizes. it's a deer, looking all around, animal fear in its
eyes. the deer finally spots its stalker, a coyote, and it attacks. the deer
moves to run away and the coyote tackles it. the deer's heart thumps louder and
louder, deeper, faster. they tumble, the deer kicks the coytote. the fear grows
deeper into its eyes. the camera pants into the deer's chest and watches as its
heart pulses and finally explodes

@sidequests
** i was only expecting a few thugs!
@detail where is the govt camp in relation to the rev. camp?
when boon approaches the govt camp, he sees two people approaching. he ducks
behind a tree. he hears the two men talking a bit frantically. they say: 
- their commander, ernst, is starting to seriously freak them out
- he also seems to have gotten really, really strong in the past few weeks
- they're afraid
- he's been claiming there is a purple-haired dogmatic made of pure evil
- they don't know if they believe him.
is possessed by one of the forsaken (but secretly)

they say that they're a bit afraid to be alone, but they're more afraid of what
ernst will do to them if he discovers that they aren't properly keeping
watch. they part ways and one begins patrolling near you. 

you go up to the first one. he nearly shits his pants when he sees you. after
speaking to you, he says that boon's not as terrifying as ernst made him
sound. boon asks more about ernst. he says that one day he walked into camp and
ernst was hanging traitors, and that his eyes had turned pure black, all
iris. he said that there he's set up rooms entirely of traps and that he stays
holed up in a room deep in the compound most of the time. 

boon asks if he's afraid, he says yes, that he just got roped into this as
a kid. the kid gives boons the layout to the base. he tells the kid to either
scram back to the rev. camp or battle him. 

the base is way way more high tech than the campground the revs have. first of
all it's an actual building. everything looks like glossy metal, it's all blocky
and slate gray. inside there are several areas

@dungeon
room ideas:
there is a mostly-deserted (as of now) barracks, like how the 2nd floor of the
office is with square hallway with rooms on the side and then a large space in
the middle
there is a boiler room that has an awesome core of purple snarling electricity
that's being powered by a dogmatic
there's an auditorium that has the entrace to a secret basement -- there are a
ton of people there, but you can make them get out (fire alarm?)
there is an officer's quarters. when you go in here, you will see ernst walking
out. he doesn't notice you. he mentions that he feels an unwieldy presence, like
a rat in his barracks. he's flecking spit as he talks. he yells almost to the
wind that he dares that slime to come challenge him face to face, and he says
he'll be waiting in the basement

journals have notes of ernst's madness. you can hear people whispering about
it. 

as you go through and hit certain spots, ernst will appear. he seems madder and
madder each time you see him, ranting about how he can practically smell boon

finally you reach his secret room. he says that boon is the one who has showed
up in his dreams, the one he saw slaying his family and drinking their blood,
the one who appears in the back of his mind and consumes it for hours at a
time. once ernst has been defeated, a spirit seeps from him. it's a message left
by the last forsaken. it says that it knew boon would be drawn here by the
threads of time. it's like a pre-recorded message, so you can't respond, and it
tells boon of the pain and suffering that his species has inflicted on the
dogmatic beings. it tells him that the humans' use of magic is tainting the
source for his kind, which is kind of akin to pissing in the water supply. can't
live like that. it says that if boon wishes to chat, triggering this message
will pass on something else that has been planted in theseus' mind. he will know
where to go.
** base & talkin' to theseus
boon returns to the camp and goes to talk to sewell and evans. they confide that
boon's tales of heroism have been going pretty far to keep the morale up, but
that they've been keeping the camp running smoothly. @detail this is more to
cover up for the fact that sewell and evans haven't really had a big part in the
plot so far. there needs to be a good warstory with the 2 or 3 of them earlier
in the story. and then probably sewell dies.

anyway, point is that they powwow a bit. evans asks how the being could have
known of theseus' existence or their associatin with him -- must be that they're
getting more powerful on this domain. he thinks that boon should ignore the
request to go talk, probably just a pity ploy to get them alone with something
that can kill them. boon disagrees, says that magical power has felt strange
inside him lately. he's new, so he wasn't sure if it was normal, but it could be
the taint they're talking about @detail would be cool if there were some random,
unexplained glitching and flashing earlier in the story (boon actually
experiencing the taint)

before they leave, they inform the revs that the entire camp is likely abandoned
or close to it. they can head in and ransack all the food they want. 

the three of them use the angreal to return to $group2's base. on seeing them,
he gives them a cheeky/confident "what the hell have you guys been up to?". he
knows some shit had to have gone down for him to get a message zapped straight
to his brain. boon tells him more or less what happened. theseus says, yeah,
that sounds about right. once boon gets to the part about humans tainting the
source, theseus has a revelation.

he says that LRB's sa'angreal may or may not be enough to defeat these beings --
we really don't know -- but you know what it would be perfect for? cutting off
humankind from the source. he must somehow know about this and be plotting to
send humankind back to the stone ages. it all makes sense! we have to stop him! 

perhaps in here: some boon disagreement, followed by some firm tess

on to the actual message: it's a true meeting request. the $thing left a
teleportation angreal somewhere, and they gotta go get it, then they can summon
it and have a chat. the angreal is being held in a small government encampment
on the foothills of the mountains. it's a place where they store and study the
various angreals and dogmatic instruments that they find but do not know what
they do with. 

theseus knows of this place, and says that it's pretty heavily guarded. as in,
this can't be a one man show. the revolutionaries finally have their mission.
** the heavily guarded shed
they all return to the base and inform the revs that they have intel that the
government is keeping some serious magical machinery locked up in a compound
down by the foothills of the mountain. tess and theseus here know a bit about it
and are willing to accompany us, in exchange for a bit of the booty. here's a
kind of funny scene with ike and tess butting heads

rousing speech to the revs, they are all super up and happy to follow their
leader into battle. boon agrees to go separately from the main party, and will
meet everyone at a rendezvous point. it is evening. you gotta walk through the
forest and then the city to make it to the foothills

@sidequests

once you make it to the point, you see all your people there. you go over the
plan with them: spread out to secure the perimeter while the powerful dogmatics
take over from inside. theseus is leading a small band of them, boon's going
alone, ike's taking a small group of them, everyone else is scattering. 

@dungeon
this one is like a more traditional dungeon, with a few caveats:
- there are a lot of cool magical artifacts
- there are notes about where these artifacts were found, theories on what they
  might do. these read like SCP entries (work is infecting my brain, i read SCP
  as SCPI)
- some of these artifacts are actually in-game hold items
- mini legend of zelda: e.g. in zelda you need the hookshot to do a certain
  dungeon then you get the feather boots or whatever. well, maybe this dungeon
  is that but on a smaller scale. each "room" has an item that you use to get
  through that room

when boon gets to the room, theseus+tess already there. theseus breathlessly
cries out when boon enters. he says that they faced problems -- dogmatics far
stronger than they anticipated. for the weaker revs that theseus was
shepherding, it was a slaughter. they are all dead. 

after a moment of looking around, tess screams. the camera pans over in time to
see her dematerialize. theseus and boon look at each other like -- was that just
an accident? did someone plan this?

boon feels a beacon call out to him -- it's tess. before being magically
shackled, she sends out a distress beacon. it tells him the general area where
she is. 

he doesn't know this, but it's in a sealed off room deeper in the dungeon. the
thing that she interacted with was a linking angreal. touch one and you're
instantly transported to where the other one is. the other one is stored in
another such room on prem. tess is basically blackout, so she's not able to just
touch the one in her room and return. her distress beacon notifies everyone in a
large radius. this is so unusual that the happening filters up to LRB himself. 

upon traversing some more dungeon, you come to where tess is. you enter the
room, and you see LRB and a couple of his cronies there prodding at her. they're
surprised to see you. they have a few of the revs, including ike, held hostage. 

they banter. boon says, hey, i know what you're up to. i know about
everything. and lrb says, yeah, i figured that. boon asks why he's doing this
when they could just join forces and try to fight it together. lrb wistfully
says that boon could never understand. finally, he says that this is not the
time to battle. humanity awaits. @detail this convo -- make LRB have just a
flash of likeability but on the whole evil. 

LRB throws down an ultimatum. we're close to figuring out how to use the
sa'angreal. so very, very close. one week more and we will unleash it against
the $things. to wait any longer would be suicide. you are an unknown
quantity. cease, desist, and let the adults handle this. 

he sets off a vortex on the other side of the room -- the camera pans, and back,
and he's gone. left there is a couple of his cronies. you pick one to fight,
theseus takes the other. the guy you fight is named lars. he's huge, shaved
bald, he's got deep set dark mean eyes. you talk briefly with him before you
battle. @detail give him a lil personality
** the meeting
before they leave the shed, boon reminds them of the reason they came here. the
reason that he remembered? he's been able to sense the angreal here the whole
time. in fact, it's right..over...there! they talk and decide that sewell +
evans + ike should return to the base to tell everyone what's up. boon, tess,
and theseus continue. 

it also tells boon about: 
the taint, what it does to their kind, and why they need humans to stop using
dogma. 
LRB is known to them, and known to be powerful, and plans to do -something- with
the sa'angreal 
the $thing reveals to boon that he is the living spirit of one of their dead
it tells him how he can save himself. surely, you have experienced strange
happenings lately? tell me of them. yes, that is the taint as sure as i have
ever heard it. they will not cease. they will drive you mad. you will become
trapped in this land of ephemeral inexistence, incorporeal, floating, for
eternity. you cannot fathom this. and if you defeat our assault against you,
this is what we will experience. taste that truth and understand why we fight
you. 

so the being, understanding that the only chance it has is to have boon close
off the portal between dimensions, will give boon the tools to do so -- even if
it means sacrificing its comrades. it tells boon where the last of its kind on
this dimension lies. it tells boon that this being holds the key to powering the
sa'angreal. it also tells boon that it is currently suffering deeply from the
taint. it is in great pain, if it can be called that. it is likely to be more
than a bit crazy. 

why are you telling us this? 
our kind our not like yours. our lives are not linear. in some way, the best
human word for what our lives are is 'predestined'. it is the necessary trade
that we accept in order to see the universe so clearly. that is not to say that
i am without motive. i think at the end of your journey you will understand our
kind much better.

and so they cease speaking. all return to the base to consult.
** rally cry!
theseus suggests that they take the whole group with them to fight the last
$thing. theseus then more or less executes the lot of them. he does this because
the less power boon has, the less he has to live for, the more likely he is to
die or sacrifice himself. is that sturdy? yeah. and then tess comes up to you
and she's like hey this happened let's kill theseus. 
** a key, a key
man, this place has to kick ass. you're hunting what is essentially a demon
that's gone mad to find a key to the most powerful channeling tool in the known
universe. 

a dungeon that becomes more reality distorted the farther you go through it

doors that don't go back to where they came from 

a world of rooms, for lack of a better term. a place that seems fey and alien,
but not altogether unlike our world. a place in three and a half
dimensions. things bleed over from the dogmatic world here. things resemble the
real world here. the light is pink. the characters faces are slightly
distorted. 
** notes
GUIDELINES
- don't forget about making the government do things that make them unlikeable
- make LRB a more important part of the story
- make boon interact with his followers more
- more than setpieces: ike, sewell, evans, tess
- theseus isn't quite a setpiece but is not fully fleshed out. what is his
  relationship with boon? 

THESEUS is going to try to use the sa'angreal to still all the humans and take
control in the power vacuum that follows
LRB is going to try to use the sa'angreal to directly battle the beings

they confront LRB, but learn that without his power humanity is lost -- so they
begrudgingly team up with him
lrb is humanity's only hope, and the being tries to trick boon into killing him
actually take out the sa'angreal, only to realize that there is a bigger threat

$group2 forces boon to lead $group1 to sacrifice themselves for the
cause. something like -- they are itching to take action against the
government. they beg boon to take them somewhere. they have a big success there,
and for the first time in this whole thing they have some momentum. but then
theseus whispers something in boon's ear, and he has to lead them on a suicide
run. he can't tell them. and at the end, before they die, they realize that
their cherished one has betrayed them. 

actually yeah. we're going with that. the framing will be that theseus is slime,
but that his brand of sliminess perfectly straddles the border between 'it
sucks, but this is what has to be done' and 'i am advancing my own interests by
sacrificing thousands of people'.

actually, that should be act 4. act 4 is where everything is about to pop -- the
government is going to use the sa'angreal, the $things are becoming more and
more corporeal, boon is feeling pressure from his role as a leader vs that of a
follower to $group2. 

act 3 needs to flesh more things out

GOALS
- flesh out theseus as a guy who's not so good
- a budding relationship between boon and tess. establish her first as what her
  shell is -- tough, unflinching, stubborn. but give them small, private moments
  of understanding (like empathy amongst equals)
- kill the third $thing, make clear that with its death the $things are now
  making great haste to enact their plan. give some semblance of what the plan
  is. 
- ratchet up the tension with the government. by the end of this act, there must
  be an ultimatum or otherwise concrete plan that they have that has to be
  stopped. 
