* Editor
@spader 3/27/19: A way to parse in TDS files without adding them to the global
scope. One problem with this is that often nodes refer to keys that exist in the
global scope, so you would have to check there to know where they are e.g.
#+BEGIN_SRC 
# foo.tds
default_foo = "bums"

# bar.tds
whatevz = {
    sup = "spum"
    foo = default_foo
}
#+END_SRC

@spader 3/27/19: A way to write out a TDS table without overwriting the whole
file. As in, find where the KVP for the table is, kill exactly that part of the
file and overwrite it. Doesn't sound too hard. 

@joey 3/28/19: Paint tiles in a different channel. @spader 4/2/19: To add to
this, it would not be much harder to just support rendering to an arbitrary
number of channels. The machinery is there (i.e. the 'z' variable in the graphic
component). The render sorts by 'z' before rendering. I'm thinking you just make
that a part of a render element instead of a component, remove all entity's
references to a Z position, and have the game (or whatever is specifying what
needs to be drawn) what channel stuff goes on. 

@spader 4/2/19: Desperately need os-safe path join!!!!!!!!
* Done!
@spader 3/26/19: Auto grid snapping isn't complete. It requires you to press ESC
to un-select a tile, because that's its cue to restore the old grid snapping
state. Need to be able to do that if you just select something in the script
selector. @done 3/27/19
@spader 3/26/19: Load tiles into levels. Everything's there, this should be real
easy. @done 3/27/19
@joey 3/28/19: Make screen less lorge based on config file.
* ?
@joey 3/28/19: Fix the grid snapping at resolutions other than 720p.
Works fine on my computer for any configuration, even if I resize the window
through native Windows drag and then reset the screen with the console.
* Install Script
string root_dir = {cwd} in src/machine_conf.hpp
install inconsolata
mark path to font dir
