intro = {
    text = [[December 14th, 2030. Celebrated by about two dozen million people on the West coast of the United States as Sovereignty Day. It started small; a few corporations building up a personal guard to protect themselves from domestic terrorism, corporate spying, and a litany of other threats. But all large things were once small. Before the large, clunky government knew what happened, the rug had been swept from under their feet. #

    This move did not go unopposed, nor unimitated. When it finally shook out, there were four nation states (if they could be called that) where the mighty United States once stood. The United States government occupied the East coast. A smallish group of final frontier types claimed the desolate hills of the north-central part of the country. The technocrats took the West coast. But most curious of all of them was what happened to America's great vast starscape: The desert. #
    
    A group of hackers (a loose term rendered even looser when every object you own has an embedded computer in it) with their finger on the pulse of geopolitics, military tech, cutting edge computing, and everything in between, realized the power vacuum was quickly approaching. The coalesced onto a ranch in central Texas, christened The Dude Ranch, about a year before everything went down. They built a community of people with many skills and many connections, proselytized the locals, and ceded while the iron was hot. #
    
    Among these people is Robert Boon. Born August '21, grew up an ordinary life as a farmhand to his father. Of course, when United Tractors started locking their hardware behind 4K RSA keys and performing some legal (with the help of a little lobbying Uncle Sam) extortion to get a nice young man to come out there with the private key and unlock them once every six months, being a farmhand wasn't as simple an occupation as it was in the past. Farmers breathe entrepreneurial spirit and self sufficience, so it only makes sense that they fit like a glove with the hacker community. #
    
    He got into computer programming when he was eleven. By fifteen, he was one of the leading security experts this side of the Mississippi. By seventeen, he realized that cracking low-grade commercial DRM was small fries, and he decided to follow the action and head to dry Nelson, Texas with a few hackers he'd come to know through his time on the internet to set up what would legendarily become known as the Dude Ranch and be at the core of a group of people who had all the skills to build a civilization. #
    
    He trained in parkour and other methods of speed and flow at the Dude Ranch. The neural augmentations didn't hurt either. Usually, in any organization, the top dogs stop getting their hands dirty real quick, and the same could be said about the FSF -- fact of the matter is, minds like those don't need to spend their time digging trenches to route springwater to a nascent pseudo-anarchist community in the middle of the desert. Boon was different. He never wanted to be anywhere but the front lines. #]]
}