// THIS FILE IS AUTOGENERATED BY METAPROGRAMMING.PY

void bind_functions() {
	auto& state = Lua.state;
	state.set_function("get_level", &get_level);
	state.set_function("add_entity", &add_entity);
	state.set_function("entity_name", &entity_name);
	state.set_function("entity_id", &entity_id);
	state.set_function("on_collide", &on_collide);
	state.set_function("update_animation", &update_animation);
	state.set_function("collider_kind", &collider_kind);
	state.set_function("draw_entity", &draw_entity);
	state.set_function("teleport_entity", &teleport_entity);
	state.set_function("move_entity", &move_entity);
	state.set_function("create_entity", &create_entity);
	state.set_function("set_animation", &set_animation);
	state.set_function("set_animation_no_reset", &set_animation_no_reset);
	state.set_function("update_entity", &update_entity);
	state.set_function("are_interacting", &are_interacting);
	state.set_function("draw_aabb", &draw_aabb);
	state.set_function("are_entities_colliding", &are_entities_colliding);
	state.set_function("register_potential_collision", &register_potential_collision);
	state.set_function("is_down", &is_down);
	state.set_function("was_down", &was_down);
	state.set_function("was_pressed", &was_pressed);
	state.set_function("go_through_door", &go_through_door);
	state.set_function("begin_dialogue", &begin_dialogue);
	state.set_function("camera_follow", &camera_follow);
}