// WARNING: THIS FILE WAS GENERATED BY generate_db_header.py

unordered_map<const char*, unordered_map<const char*, int>> db_schema = {
	{
		"levels", {
			{"name", 0}
		}
	},
	{
		"entities", {
			{"lua_id", 0},
			{"game_id", 1},
			{"level", 2}
		}
	},
	{
		"position_components", {
			{"x", 0},
			{"y", 1},
			{"entity", 2}
		}
	},
	{
		"state", {
			{"name", 0},
			{"value", 1}
		}
	},
	{
		"entity_state", {
			{"name", 0},
			{"state", 1}
		}
	}
};