// THIS FILE IS AUTOGENERATED BY entity_tree.py

unordered_map<string, vector<string>> script_to_entity = {
	{
		"buildings/boonhouse.tds",
		{"boonhouse_door"}
	},
	{
		"buildings/cantina.tds",
		{"building", "table", "chair_left", "chair_right", "bar", "liquor_cabinet", "bookcase", "picture"}
	},
	{
		"characters/boi.tds",
		{"boi"}
	},
	{
		"characters/hero.tds",
		{"boon"}
	},
	{
		"characters/intro_police.tds",
		{"intro_police"}
	},
	{
		"characters/wilson/scenes/intro.tds",
		{"wilson"}
	},
	{
		"props/fences.tds",
		{"fence_left", "fence_middle", "fence_right", "fence_post", "fence_top"}
	},
	{
		"props/foliage.tds",
		{"tree", "cactus", "bush"}
	},
	{
		"props/tiles.tds",
		{"grass", "grass_flower1", "grass_flower2", "grass_flower3", "sand", "sand_cracked", "sand_path_top", "sand_path_bottom", "sand_path_left", "sand_path_right", "sand_path_topleft_inner", "sand_path_topright_inner", "sand_path_bottomleft_inner", "sand_path_bottomright_inner", "sand_path_topleft_outer", "sand_path_topright_outer", "sand_path_bottomleft_outer", "border_left_sand_grass", "sand_path_bottomright_outer", "border_bottom_sand_grass", "border_top_sand_grass", "border_right_sand_grass", "border_bottom_right_sand_grass", "border_bottom_left_sand_grass", "border_top_left_sand_grass", "border_top_right_sand_grass", "border_bottom_right_grass", "border_bottom_left_grass", "border_top_left_grass", "border_top_right_grass", "wood_floor"}
	}
};